config/routes.rb
Rails.application.routes.draw do
  # resources :generalledgers
  resources :cashiers do
    resources :generalledgers, module: :cashiers
  end
  resources :agents
  resources :payments
  resources :check_vouchers do
    resources :generalledgers, module: :check_vouchers
  end
  resources :periods
  resources :journal_vouchers do
    resources :generalledgers, module: :journal_vouchers
  end
  resources :accounts
  resources :banks
  resources :branches
  resources :sub_accounts
  resources :payees
  resources :ledgers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
end

app/models/account.rb
class Account < ApplicationRecord
    validates_presence_of :account_title
    # belongs_to :Account
    def to_s
        account_title
    end
end

app/models/agent.rb
class Agent < ApplicationRecord 
  validates_presence_of :agent_name
  belongs_to :branch
  
  def to_s
    agent_name
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
    validates_presence_of :bank_title
    belongs_to :branch

    def to_s
        bank_title
    end
end

app/models/branch.rb
class Branch < ApplicationRecord
    validates_presence_of :branch_name
    def to_s
        branch_name
    end
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  validates_presence_of :orno, :amount_paid, :amount_deposit
  belongs_to :payee
  belongs_to :payment
  belongs_to :agent
  belongs_to :bank
  # has_many :generalledgers as: :ledgerable
  has_many :ledgers, as: :ledgerable
end

app/models/check_voucher.rb
class CheckVoucher < ApplicationRecord
  belongs_to :payee
  belongs_to :bank

  has_many :ledgers, as: :ledgerable
  accepts_nested_attributes_for :ledgers, reject_if: :all_blank, allow_destroy: true
end

app/models/generalledger.rb
class Generalledger < ApplicationRecord
  belongs_to :account
  belongs_to :branch
  belongs_to :sub_account
  belongs_to :ledgerable, polymorphic: true
end

app/models/journal_voucher.rb
class JournalVoucher < ApplicationRecord
  belongs_to :payee
  belongs_to :period
  belongs_to :branch
  # has_many :generalledgers as: :ledgerable
  has_many :ledgers, as: :ledgerable
end

app/models/ledger.rb
class Ledger < ApplicationRecord
  attr_accessor :temp_amount
  
  validates_presence_of :account, :entry_type
  belongs_to :account, optional: true
  belongs_to :sub_account, optional: true
  belongs_to :ledgerable, polymorphic: true, optional: true

  ACCOUNT_ENTRY = ["Debit","Credit"]

  
end

app/models/payee.rb
class Payee < ApplicationRecord
    validates_presence_of :payee


    def to_s
        payee
    end
end

app/models/payment.rb
class Payment < ApplicationRecord
    validates_presence_of :payment_title
    def to_s
        payment_title
    end
    
end

app/models/period.rb
class Period < ApplicationRecord
    validates_presence_of :period_title
    def to_s
        period_title
    end
end

app/models/sub_account.rb
class SubAccount < ApplicationRecord
    validates_presence_of :sub_account_title
    def to_s
        sub_account_title
    end
end

app/controllers/ledgers_controller.rb
class LedgersController < ApplicationController
    before_action :set_ledger, only: %i[ show edit update destroy ]

    def show

    end

    def index
        @ledger = Ledger.all
    end

    def new
      # raise 'errors'
      if params[:type] == 'JV'
        @check_voucher = JournalVoucher.find(params[:v])
      elsif params[:type] == 'CV'
        @check_voucher = CheckVoucher.find(params[:v])
      elsif params[:type] == 'OR'
        @check_voucher = Cashier.find(params[:v])
      end
        @type = params[:type]
        # @check_voucher = JournalVoucher.find(params[:cv])
        @ledger = @check_voucher.ledgers.build #Ledger.new
    end

    def create
      # raise 'errors'
      if params[:type] == 'JV'
        @check_voucher = JournalVoucher.find(params[:v])
        @ledger =  @check_voucher.ledgers.build(ledger_params)
        @ledger.reference = @check_voucher.voucher
      elsif params[:type] == 'CV'
        @check_voucher = CheckVoucher.find(params[:v])
        @ledger =  @check_voucher.ledgers.build(ledger_params)
        @ledger.reference = @check_voucher.voucher
      elsif params[:type] == 'OR'
        @check_voucher = Cashier.find(params[:v])
        @ledger =  @check_voucher.ledgers.build(ledger_params)
        @ledger.reference = @check_voucher.orno
      end
      # @check_voucher = CheckVoucher.find(params[:v])
      # puts @check_voucher
      
      
      # @ledger =  @check_voucher.ledgers.build(ledger_params)
      if @ledger.entry_type == "Debit"
        @ledger.debit = ledger_params[:temp_amount]
        @ledger.credit = 0
      else
        @ledger.credit = ledger_params[:temp_amount]
        @ledger.debit = 0
      end
      respond_to do |format|
        if @check_voucher.ledgers << @ledger #@ledger.save
          # format.turbo_stream do
          #    render turbo_stream: turbo_stream.append("check_voucher", partial: 'check_vouchers/ledger_entry', locals: {check_vouchers: show})
          # end
          format.html { redirect_back fallback_location: @check_voucher, notice: "An account was entered." }
          format.json { render :show, status: :created, location: @ledger }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @ledger.errors, status: :unprocessable_entity }
          format.turbo_stream { render :form_update, status: :unprocessable_entity }
        end
      end
    end

    def edit
      if @ledger.entry_type == "Debit"
        @temp_amount = @ledger.debit
      else
        @temp_amount = @ledger.credit
      end
    end

    def update
      # raise 'errors'
        @ledger.entry_type = ledger_params[:entry_type]
      if ledger_params[:entry_type] == "Debit"
        @ledger.debit = ledger_params[:temp_amount]
        # @ledger.credit = 0
      else
        @ledger.credit = ledger_params[:temp_amount]
        @ledger.debit = 0
      end

      respond_to do |format|
        if @ledger.update(ledger_params)
          format.html { redirect_back fallback_location: @check_voucher, notice: "Ledger was updated" }
          format.json { render :show, status: :created, location: @ledger }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @ledger.errors, status: :unprocessable_entity }
          format.turbo_stream { render :form_update, status: :unprocessable_entity }
        end
      end
    end
    private

    def set_ledger
      @ledger = Ledger.find(params[:id])
    end

    def ledger_params
        params.require(:ledger).permit(:id, :account_id, :sub_account_id, :reference, :entry_type, :debit, :credit, :temp_amount)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/ledgers/_form.html.erb
<%= simple_form_for(@ledger, url: url, method: meth) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs mb-3">
   
    <%= f.association :account, prompt: "Choose account", input_html: { class: 'form-select' } %>
    <%= f.association :sub_account, prompt: "Choose sub-account", input_html: { class: 'form-select' } %>
    <%= f.input :entry_type, collection: Ledger::ACCOUNT_ENTRY, wrapper_html: { class: 'col-md' } %>
    <%#= f.input :debit, label: "Amount" %>
     <%= f.input :temp_amount, label: "Amount", input_html: { value: @temp_amount } %>
 </div>
  <div class="form-actions text-end">
    
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/ledgers/_ledger_entry.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Account</th>
      <th>Sub-account</th>
      <th class="text-end">Debit</th>
      <th class="text-end">Credit</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @voucher.ledgers.each do |ledger| %>
      <tr id=<%= dom_id(ledger) %>>
        <td><%= ledger.id %></td>
        <td><%= ledger.account %></td>
        <td><%= ledger.sub_account %></td>
        <td class="text-end"><%= number_to_currency(ledger.debit, :unit => "") %></td>
        <td class="text-end"><%= number_to_currency(ledger.credit, :unit => "") %></td>
        <td>
          <%= link_to 'Edit', edit_ledger_path(ledger), data: { turbo_frame: "remote_modal" }, class: 'btn'  %>
          <%= link_to 'Delete', ledger, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: 'btn' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot class="fw-bold">
    <td></td>
    <td colspan="2" class="table-active">TOTAL</td>
    <td class="text-end"><%= number_to_currency(@total_debit, :unit => "") %></td>
    <td class="text-end"><%= number_to_currency(@total_credit, :unit => "") %></td>
  </tfoot>
</table>

app/views/ledgers/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>

    <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body remote_modal_body" id="remote_modal_body">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/ledgers/edit.html.erb
<%= render "remote_modal", title: "Edit Account" do %>
  <%= render "form", url: ledger_path(@ledger), meth: 'patch'  %>
<% end %>

app/views/ledgers/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form", item: @item %>
<% end %>

app/views/ledgers/index.html.erb
<h1>Ledger ka </h1>
<%= link_to new_ledger_path, class: 'btn btn-primary' do %>
    New Ledger
<% end%>

app/views/ledgers/new.html.erb
<%= render "remote_modal", title: "Enter Account" do %>
  <%# <div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd"> %>
    <%= render "form", url: ledgers_path(v: @check_voucher, type: @type), meth: 'post' %>
  <%# </div> %>
<% end %>
 

app/views/ledgers/show.html.erb
<h1>Show Ledger</h1>