config/routes.rb
Rails.application.routes.draw do
  # resources :generalledgers
  resources :cashiers do
    resources :generalledgers, module: :cashiers
  end
  resources :agents
  resources :payments
  resources :check_vouchers do
    resources :generalledgers, module: :check_vouchers
  end
  resources :periods
  resources :journal_vouchers do
    resources :generalledgers, module: :journal_vouchers
  end
  resources :accounts
  resources :banks
  resources :branches
  resources :sub_accounts
  resources :payees
  resources :ledgers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
end

app/models/account.rb
class Account < ApplicationRecord
    validates_presence_of :account_title
    # belongs_to :Account
    def to_s
        account_title
    end
end

app/models/agent.rb
class Agent < ApplicationRecord 
  validates_presence_of :agent_name
  belongs_to :branch
  
  def to_s
    agent_name
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
    validates_presence_of :bank_title
    belongs_to :branch

    def to_s
        bank_title
    end
end

app/models/branch.rb
class Branch < ApplicationRecord
    validates_presence_of :branch_name
    def to_s
        branch_name
    end
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  validates_presence_of :orno, :amount_paid, :amount_deposit
  belongs_to :payee
  belongs_to :payment
  belongs_to :agent
  belongs_to :bank
  # has_many :generalledgers as: :ledgerable
  has_many :ledgers, as: :ledgerable
end

app/models/check_voucher.rb
class CheckVoucher < ApplicationRecord
  belongs_to :payee
  belongs_to :bank

  has_many :ledgers, as: :ledgerable
  accepts_nested_attributes_for :ledgers, reject_if: :all_blank, allow_destroy: true
end

app/models/generalledger.rb
class Generalledger < ApplicationRecord
  belongs_to :account
  belongs_to :branch
  belongs_to :sub_account
  belongs_to :ledgerable, polymorphic: true
end

app/models/journal_voucher.rb
class JournalVoucher < ApplicationRecord
  belongs_to :payee
  belongs_to :period
  belongs_to :branch
  # has_many :generalledgers as: :ledgerable
  has_many :ledgers, as: :ledgerable
end

app/models/ledger.rb
class Ledger < ApplicationRecord
  attr_accessor :temp_amount
  
  validates_presence_of :account, :entry_type
  belongs_to :account, optional: true
  belongs_to :sub_account, optional: true
  belongs_to :ledgerable, polymorphic: true, optional: true

  ACCOUNT_ENTRY = ["Debit","Credit"]

  
end

app/models/payee.rb
class Payee < ApplicationRecord
    validates_presence_of :payee


    def to_s
        payee
    end
end

app/models/payment.rb
class Payment < ApplicationRecord
    validates_presence_of :payment_title
    def to_s
        payment_title
    end
    
end

app/models/period.rb
class Period < ApplicationRecord
    validates_presence_of :period_title
    def to_s
        period_title
    end
end

app/models/sub_account.rb
class SubAccount < ApplicationRecord
    validates_presence_of :sub_account_title
    def to_s
        sub_account_title
    end
end

app/controllers/sub_accounts_controller.rb
class SubAccountsController < ApplicationController
  before_action :set_sub_account, only: %i[ show edit update destroy ]

  # GET /sub_accounts or /sub_accounts.json
  def index
    @sub_accounts = SubAccount.all
  end

  # GET /sub_accounts/1 or /sub_accounts/1.json
  def show
  end

  # GET /sub_accounts/new
  def new
    @sub_account = SubAccount.new
  end

  # GET /sub_accounts/1/edit
  def edit
  end

  # POST /sub_accounts or /sub_accounts.json
  def create
    @sub_account = SubAccount.new(sub_account_params)

    respond_to do |format|
      if @sub_account.save
        format.html { redirect_to sub_account_url(@sub_account), notice: "Sub account was successfully created." }
        format.json { render :show, status: :created, location: @sub_account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sub_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_accounts/1 or /sub_accounts/1.json
  def update
    respond_to do |format|
      if @sub_account.update(sub_account_params)
        format.html { redirect_to sub_account_url(@sub_account), notice: "Sub account was successfully updated." }
        format.json { render :show, status: :ok, location: @sub_account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sub_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_accounts/1 or /sub_accounts/1.json
  def destroy
    @sub_account.destroy

    respond_to do |format|
      format.html { redirect_to sub_accounts_url, notice: "Sub account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_account
      @sub_account = SubAccount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_account_params
      params.require(:sub_account).permit(:sub_account_title, :description)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/helpers/sub_accounts_helper.rb
module SubAccountsHelper
end

app/views/sub_accounts/_form.html.erb
<%= simple_form_for(@sub_account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs mb-3">
    <%= f.input :sub_account_title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions text-end">
    <%= link_to "Back", sub_accounts_path, class: 'btn btn-secondary' %>
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/sub_accounts/_sub_account.html.erb
<div id="<%= dom_id sub_account %>">
  <p>
    <strong>Subaccount title:</strong>
    <%= sub_account.sub_account_title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= sub_account.description %>
  </p>

</div>

app/views/sub_accounts/edit.html.erb
<div class="card">
  <div class="card-header">
      <h1>Editing sub account</h1>
  </div>
  <div class="card-body">
    <%= render "form", sub_account: @sub_account %>
  </div>
    <br>
    <div class="card-footer">
      <%= link_to "Back", sub_accounts_path, class: 'btn btn-primary' %>
    </div>

app/views/sub_accounts/index.html.erb
<%= content_tag :h1, "List of Sub Accounts" %>


<div class="text-end mb-3">
  <%= link_to new_sub_account_path, class: 'btn btn-primary' do %>
    New Sub Account
  <% end %>
</div>

<table class ="table table-striped">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>

      <th>ID</th>
        <th>Subaccount Title</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>

    
      <% @sub_accounts.each do |sub_account| %>
        <tr>

        <td><%= sub_account.id %></td>
        <td><%= sub_account.sub_account_title %></td>
        <td><%= sub_account.description %></td>
    
          <td>
            <%= link_to 'View', sub_account, class: 'btn' %>
            <%= link_to 'Edit', edit_sub_account_path(sub_account), class: 'btn' %>
            <%= link_to 'Delete', sub_account, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sub_accounts/new.html.erb
<div class="card">
  <div class="card-header">
      <h1>Create Sub-Account</h1>
  </div>
  <div class="card-body">
    <%= render "form", sub_account: @sub_account %>
  </div>
    <br>
    <div class="card-footer">
      <%= link_to "Back", sub_accounts_path, class: 'btn btn-primary' %>
    </div>

app/views/sub_accounts/show.html.erb
<div class="card">
  
  <div class="card-header">
    <h3>Payee details</h3>
    <%= button_to "Delete", @sub_account, method: :delete, class: 'btn btn-danger' %>
  </div>
  <div class="card-body">
    
    <%= render @sub_account %>
  </div>
  <div class="card-footer">
    <%= link_to "Edit", edit_sub_account_path(@sub_account), class: "btn btn-secondary btn-sm" %> |
  <%= link_to "Back", sub_accounts_path, class: "btn btn-secondary btn-sm" %>
  </div>

</div>