config/routes.rb
Rails.application.routes.draw do
  # resources :generalledgers
  resources :cashiers do
    resources :generalledgers, module: :cashiers
  end
  resources :agents
  resources :payments
  resources :check_vouchers do
    resources :generalledgers, module: :check_vouchers
  end
  resources :periods
  resources :journal_vouchers do
    resources :generalledgers, module: :journal_vouchers
  end
  resources :accounts
  resources :banks
  resources :branches
  resources :sub_accounts
  resources :payees
  resources :ledgers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
end

app/models/account.rb
class Account < ApplicationRecord
    validates_presence_of :account_title
    # belongs_to :Account
    def to_s
        account_title
    end
end

app/models/agent.rb
class Agent < ApplicationRecord 
  validates_presence_of :agent_name
  belongs_to :branch
  
  def to_s
    agent_name
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
    validates_presence_of :bank_title
    belongs_to :branch

    def to_s
        bank_title
    end
end

app/models/branch.rb
class Branch < ApplicationRecord
    validates_presence_of :branch_name
    def to_s
        branch_name
    end
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  validates_presence_of :orno, :amount_paid, :amount_deposit
  belongs_to :payee
  belongs_to :payment
  belongs_to :agent
  belongs_to :bank
  # has_many :generalledgers as: :ledgerable
  has_many :ledgers, as: :ledgerable
end

app/models/check_voucher.rb
class CheckVoucher < ApplicationRecord
  belongs_to :payee
  belongs_to :bank

  has_many :ledgers, as: :ledgerable
  accepts_nested_attributes_for :ledgers, reject_if: :all_blank, allow_destroy: true
end

app/models/generalledger.rb
class Generalledger < ApplicationRecord
  belongs_to :account
  belongs_to :branch
  belongs_to :sub_account
  belongs_to :ledgerable, polymorphic: true
end

app/models/journal_voucher.rb
class JournalVoucher < ApplicationRecord
  belongs_to :payee
  belongs_to :period
  belongs_to :branch
  # has_many :generalledgers as: :ledgerable
  has_many :ledgers, as: :ledgerable
end

app/models/ledger.rb
class Ledger < ApplicationRecord
  attr_accessor :temp_amount
  
  validates_presence_of :account, :entry_type
  belongs_to :account, optional: true
  belongs_to :sub_account, optional: true
  belongs_to :ledgerable, polymorphic: true, optional: true

  ACCOUNT_ENTRY = ["Debit","Credit"]

  
end

app/models/payee.rb
class Payee < ApplicationRecord
    validates_presence_of :payee


    def to_s
        payee
    end
end

app/models/payment.rb
class Payment < ApplicationRecord
    validates_presence_of :payment_title
    def to_s
        payment_title
    end
    
end

app/models/period.rb
class Period < ApplicationRecord
    validates_presence_of :period_title
    def to_s
        period_title
    end
end

app/models/sub_account.rb
class SubAccount < ApplicationRecord
    validates_presence_of :sub_account_title
    def to_s
        sub_account_title
    end
end

app/controllers/check_vouchers_controller.rb
class CheckVouchersController < ApplicationController
  before_action :set_check_voucher, only: %i[ show edit update destroy ]

  # GET /check_vouchers or /check_vouchers.json
  def index
    @check_vouchers = CheckVoucher.all
  end

  # GET /check_vouchers/1 or /check_vouchers/1.json
  def show
    @total_debit = @check_voucher.ledgers.where(entry_type: "Debit").sum(:debit)
    @total_credit = @check_voucher.ledgers.where(entry_type: "Credit").sum(:credit)
  end

  # GET /check_vouchers/new
  def new
    @check_voucher = CheckVoucher.new
  end

  # GET /check_vouchers/1/edit
  def edit
  end

  # POST /check_vouchers or /check_vouchers.json
  def create
    @check_voucher = CheckVoucher.new(check_voucher_params)

    respond_to do |format|
      if @check_voucher.save
        
        format.html { redirect_to check_voucher_url(@check_voucher), notice: "Check voucher was successfully created." }
        format.json { render :show, status: :created, location: @check_voucher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @check_voucher.errors, status: :unprocessable_entity }
        
      end
    end
  end

  # PATCH/PUT /check_vouchers/1 or /check_vouchers/1.json
  def update
    respond_to do |format|
      if @check_voucher.update(check_voucher_params)
        format.html { redirect_to check_voucher_url(@check_voucher), notice: "Check voucher was successfully updated." }
        format.json { render :show, status: :ok, location: @check_voucher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @check_voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_vouchers/1 or /check_vouchers/1.json
  def destroy
    @check_voucher.destroy

    respond_to do |format|
      format.html { redirect_to check_vouchers_url, notice: "Check voucher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_voucher
      @check_voucher = CheckVoucher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def check_voucher_params
      params.require(:check_voucher).permit(:payee_id, :bank_id, :voucher, :date_voucher, :address, :description, :amount,
      ledgers_attributes: [:id, :account_id, :reference, :entry_type, :debit, :credit, :_destroy])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/check_vouchers_helper.rb
module CheckVouchersHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/views/check_vouchers/_check_voucher.html.erb
<div id="<%= dom_id check_voucher %>">
  <%#= content_tag :p, %>
  <%= content_tag :h1, 'Check Voucher', class:"mb-3" %>
  <%= content_tag :div, class: "card" do %>
    <%= content_tag :div, class: "card-header" do %>
      <%= content_tag :p, "Voucher", class: "small text-muted mb-0" %>
      <%= content_tag(:div, content_tag(:p, check_voucher.voucher, class: "fs-2 text-primary mb-0"), class: "card-title") %>
      <%= content_tag(:p, check_voucher.description, class: "card-text small") %>
    <% end %>
    <%= content_tag :div, class: "card-body" do %>
      <%= content_tag :dl, class: "row" do %>
        <%= content_tag :dt, "Date voucher:", class:"col-sm-2"  %>
        <%= content_tag :dd, check_voucher.date_voucher, class: "col-sm-10" %>
        <%= content_tag :dt, "Payee:", class:"col-sm-2" %>
        <%= content_tag :dd, class: "col-sm-10" do %>
          <%= content_tag :p, check_voucher.payee, class: "mb-1" %>
          <%= content_tag :p, check_voucher.address, class: "mb-1 small" %>
        <% end %>
        <%= content_tag :dt, 'Bank:', class:"col-sm-2" %>
        <%= content_tag :dd, check_voucher.bank, class:"col-sm-10" %>
        <%= content_tag :dt, 'Amount:',class:"col-sm-2" %>
        <%= content_tag :dd, number_to_currency(check_voucher.amount, unit: ""), class:"col-sm-10" %>
      <% end %>
      
    <% end %>
    <%= content_tag :div, class: "card-footer" do %>
      <%= link_to 'Delete', check_voucher, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: 'btn btn-danger btn-sm' %>
      <%= link_to "Edit", edit_check_voucher_path(@check_voucher), class: "btn btn-secondary btn-sm" %> |
      <%= link_to "Back", check_vouchers_path, class: "btn btn-secondary btn-sm" %>
    <% end %>
  <% end %>
</div>

app/views/check_vouchers/_form.html.erb
<%= simple_form_for(@check_voucher) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs mb-3">
    <%= f.input :voucher %>
    <%= f.input :date_voucher %>
    <%= f.association :payee %>
    <%= f.association :bank %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :amount %>
  </div>

  
  <%#= link_to_add_nested(f, :ledgers, '#ledgerentry', link_classes: "btn btn-primary", partial_form_variable: :ff) %>
  <%# <div class="row">
    <div id="ledgerentry"> %>
      <%#= f.simple_fields_for :ledgers do |lf| %>
        <%#=# render 'ledger_fields', form: lf %>
      <%# end %>
    <%# </div>
  </div> %>
  <div class="form-actions text-end">
    <%= link_to "Back", check_vouchers_path, class: 'btn btn-secondary' %>
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/check_vouchers/_ledger_entry.html.erb
   
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Account</th>
      <th>Sub-account</th>
      <th>Entry Type</th>
      <th>Debit</th>
      <th>Credit</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @check_voucher.ledgers.each do |ledger| %>
      <tr id=<%= dom_id(ledger) %>>
        <td><%= ledger.id %></td>
        <td><%= ledger.account %></td>
        <td><%= ledger.sub_account %></td>
        <td><%= ledger.entry_type %></td>
        <td><%= ledger.debit %></td>
        <td><%= ledger.credit %></td>
        <td>
          <%= link_to 'Edit', edit_ledger_path(ledger), data: { turbo_frame: "remote_modal" }, class: 'btn'  %>
          <%= link_to 'Delete', ledger, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: 'btn' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/check_vouchers/_ledger_fields.html.erb
<h1>test me</h1>

app/views/check_vouchers/_remote_modal.html.erb
<%= turbo_frame_tag "remote_modal" do %>

    <div class="modal fade" id="shareRecipeModal" tabindex="-1" aria-labelledby="newItemRemoteModalLabel" aria-hidden="true" data-controller="remote-modal" data-action="turbo:before-render@document->remote-modal#hideBeforeRender">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content" id="modal_content">
                <div class="modal-header">
                    <h4 class="modal-title" id="newItemRemoteModalLabel"><%= title %></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body remote_modal_body" id="remote_modal_body">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>

<% end %>

app/views/check_vouchers/edit.html.erb
<div class="card">
  <div class="card-header">
      <h1>Editing check voucher</h1>
  </div>
  <div class="card-body">
    <%= render "form", check_voucher: @check_voucher %>
  </div>
    <br>
    <div class="card-footer">
      <%= link_to "Back", check_vouchers_path, class: 'btn btn-primary' %>
    </div>

app/views/check_vouchers/index.html.erb
<%= content_tag :h1, "List of Check Vouchers" %>


<div class="text-end mb-3">
  <%= link_to new_check_voucher_path, class: 'btn btn-primary' do %>
    New Check Voucher
  <% end %>
</div>

<table class ="table table-striped">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>

      <th>ID</th>
        
        <th>Voucher</th>
        <th>Date Voucher</th>
        <th>Payee</th>
        <th>Bank</th>
        <th>Description</th>
        <th>Amount</th>
        <th></th>

      </tr>
    </thead>

    <tbody>
      <% @check_vouchers.each do |check_voucher| %>
        <tr>

        <td><%= check_voucher.id %></td>
        <td><%= check_voucher.voucher %></td>
        <td><%= check_voucher.date_voucher %></td>
        <td><%= check_voucher.payee %></td>
        <td><%= check_voucher.bank %></td>
        <td class="small"><%= check_voucher.description %></td>
        <td><%= number_to_currency(check_voucher.amount, :unit => "") %></td>
    
          <td>
            <%= link_to 'View', check_voucher, class: 'btn' %>
            <%= link_to 'Edit', edit_check_voucher_path(check_voucher), class: 'btn' %>
            <%= link_to 'Delete', check_voucher, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/check_vouchers/ledger.html.erb
<div class="card">
  <div class="card-header">
    <h1>New check voucher</h1>
  </div>
  <div class="card-body">
    <%= render "remote_modal", title: "New item" do %>
      <%= ff.association :account %>
      <%= ff.input :entry_type %>
      <%= ff.input :debit %>
      <%= ff.input :credit %>
      <%= link_to_remove_nested(ff, link_text: "Remove") %>
    </div>
  <% end %>
</div>
<br>
<div class="card-footer">
  <%= link_to "Back", check_vouchers_path, class: 'btn btn-primary' %>
</div>

app/views/check_vouchers/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>New check voucher</h1>
  </div>
  <div class="card-body">
    <%#= render "remote_modal", title: "New item" do %>
      <%= render "form", check_voucher: @check_voucher %>
      <%# end %>
    </div>
    <br>
    <div class="card-footer">
      <%= link_to "Back", check_vouchers_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/check_vouchers/show.html.erb
<div>
  <%= render @check_voucher %>
</div>
<div class="text-end">
  
  <%= link_to '<i class="bi bi-plus-square"></i> New item'.html_safe, new_ledger_path(v: @check_voucher, type: 'CV'), class: "btn btn-primary mb-3 mt-3", data: { turbo_frame: "remote_modal" } %>
</div>
<%= turbo_frame_tag "ledger_items" do %>
  <% @voucher = @check_voucher %>
  <div id="ledger-items-table">
    <%= render 'ledgers/ledger_entry' %>
  </div>
<% end %>
</div>