config/routes.rb
Rails.application.routes.draw do
  # resources :generalledgers
  resources :cashiers do
    resources :generalledgers, module: :cashiers
  end
  resources :agents
  resources :payments
  resources :check_vouchers do
    resources :generalledgers, module: :check_vouchers
  end
  resources :periods
  resources :journal_vouchers do
    resources :generalledgers, module: :journal_vouchers
  end
  resources :accounts
  resources :banks
  resources :branches
  resources :sub_accounts
  resources :payees
  resources :ledgers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
end

app/models/account.rb
class Account < ApplicationRecord
    validates_presence_of :account_title
    # belongs_to :Account
    def to_s
        account_title
    end
end

app/models/agent.rb
class Agent < ApplicationRecord 
  validates_presence_of :agent_name
  belongs_to :branch
  
  def to_s
    agent_name
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
    validates_presence_of :bank_title
    belongs_to :branch

    def to_s
        bank_title
    end
end

app/models/branch.rb
class Branch < ApplicationRecord
    validates_presence_of :branch_name
    def to_s
        branch_name
    end
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  validates_presence_of :orno, :amount_paid, :amount_deposit
  belongs_to :payee
  belongs_to :payment
  belongs_to :agent
  belongs_to :bank
  # has_many :generalledgers as: :ledgerable
  has_many :ledgers, as: :ledgerable
end

app/models/check_voucher.rb
class CheckVoucher < ApplicationRecord
  belongs_to :payee
  belongs_to :bank

  has_many :ledgers, as: :ledgerable
  accepts_nested_attributes_for :ledgers, reject_if: :all_blank, allow_destroy: true
end

app/models/generalledger.rb
class Generalledger < ApplicationRecord
  belongs_to :account
  belongs_to :branch
  belongs_to :sub_account
  belongs_to :ledgerable, polymorphic: true
end

app/models/journal_voucher.rb
class JournalVoucher < ApplicationRecord
  belongs_to :payee
  belongs_to :period
  belongs_to :branch
  # has_many :generalledgers as: :ledgerable
  has_many :ledgers, as: :ledgerable
end

app/models/ledger.rb
class Ledger < ApplicationRecord
  attr_accessor :temp_amount
  
  validates_presence_of :account, :entry_type
  belongs_to :account, optional: true
  belongs_to :sub_account, optional: true
  belongs_to :ledgerable, polymorphic: true, optional: true

  ACCOUNT_ENTRY = ["Debit","Credit"]

  
end

app/models/payee.rb
class Payee < ApplicationRecord
    validates_presence_of :payee


    def to_s
        payee
    end
end

app/models/payment.rb
class Payment < ApplicationRecord
    validates_presence_of :payment_title
    def to_s
        payment_title
    end
    
end

app/models/period.rb
class Period < ApplicationRecord
    validates_presence_of :period_title
    def to_s
        period_title
    end
end

app/models/sub_account.rb
class SubAccount < ApplicationRecord
    validates_presence_of :sub_account_title
    def to_s
        sub_account_title
    end
end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController
  before_action :set_payee, only: %i[ show edit update destroy ]

  # GET /payees or /payees.json
  def index
    @payees = Payee.all
  end

  # GET /payees/1 or /payees/1.json
  def show
  end

  # GET /payees/new
  def new
    @payee = Payee.new
  end

  # GET /payees/1/edit
  def edit
  end

  # POST /payees or /payees.json
  def create
    @payee = Payee.new(payee_params)

    respond_to do |format|
      if @payee.save
        format.html { redirect_to payee_url(@payee), notice: "Payee was successfully created." }
        format.json { render :show, status: :created, location: @payee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payees/1 or /payees/1.json
  def update
    respond_to do |format|
      if @payee.update(payee_params)
        format.html { redirect_to payee_url(@payee), notice: "Payee was successfully updated." }
        format.json { render :show, status: :ok, location: @payee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payees/1 or /payees/1.json
  def destroy
    @payee.destroy

    respond_to do |format|
      format.html { redirect_to payees_url, notice: "Payee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payee
      @payee = Payee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payee_params
      params.require(:payee).permit(:payee, :address, :description)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payees/_form.html.erb
<%= simple_form_for(@payee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :payee %>
    <%= f.input :address %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <br>
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/payees/_payee.html.erb
<div id="<%= dom_id payee %>">
  <p>
    <strong>Payee:</strong>
    <%= payee.payee %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= payee.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= payee.description %>
  </p>

</div>

app/views/payees/edit.html.erb
<h1>Editing payee</h1>

<%= render "form", payee: @payee %>

<br>

<div>
  <%= link_to "Show this payee", @payee %> |
  <%= link_to "Back to payees", payees_path %>
</div>

app/views/payees/index.html.erb
<div class="alert alert-primary" role="alert">
  <%= notice %>
</div>

<h1>Payees</h1>
<div class="text-end mb-3">
  <%= link_to "New payee", new_payee_path ,class: "btn btn-primary" %>
</div>
<table class ="table table-striped">
  <thead>
    <tr>
      <th>Payee</th>
      <th>Address</th>
      <th>Description</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @payees.each do |payee| %>
      <tr>
        <td><%= payee.payee %></td>
        <td><%= payee.address %></td>
        <td><%= payee.description %></td>
        <td><%= link_to "Show this payee", payee %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/payees/new.html.erb
<div class="card">
  <div class="card-header">
      <h1>New payee</h1>
  </div>
  <div class="card-body">
    <%= render "form", payee: @payee %>
  </div>
    <br>
    <div class="card-footer">
      <%= link_to "Back to payees", payees_path %>
    </div>
</div>

app/views/payees/show.html.erb
<div class="card">
  
  <div class="card-header">
    <h3>Payee details</h3>
    <%= button_to "Destroy this payee", @payee, method: :delete , class: "btn btn-primary"%>
  </div>
  <div class="card-body">
    
    <%= render @payee %>
  </div>
  <div class="card-footer">
    <%= link_to "Edit this payee", edit_payee_path(@payee), class: "btn btn-secondary btn-sm" %> |
    <%= link_to "Back to payees", payees_path, class: "btn btn-secondary btn-sm" %>

    
  </div>

</div>